---
  - name: Basically "apt-get update"
    apt:
      update_cache: yes

  - name: Install NGINX Packages
    apt:
      name: nginx
      state: latest

  - name: generate Nginx site config
    template:
      src: ~/FelCloud/index.html
      dest: /var/www/html/index.html

  - name: Start Service
    service:
      name: nginx
      state: restarted
      enabled: yes


